/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1McpRouteImport } from './routes/api/v1/mcp'
import { Route as ApiV1DotwellKnownOauthProtectedResourceRouteImport } from './routes/api/v1/[.]well-known/oauth-protected-resource'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1McpRoute = ApiV1McpRouteImport.update({
  id: '/api/v1/mcp',
  path: '/api/v1/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DotwellKnownOauthProtectedResourceRoute =
  ApiV1DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/api/v1/.well-known/oauth-protected-resource',
    path: '/api/v1/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/api/v1/.well-known/oauth-protected-resource': typeof ApiV1DotwellKnownOauthProtectedResourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/api/v1/.well-known/oauth-protected-resource': typeof ApiV1DotwellKnownOauthProtectedResourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/api/v1/.well-known/oauth-protected-resource': typeof ApiV1DotwellKnownOauthProtectedResourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/v1/mcp'
    | '/api/v1/.well-known/oauth-protected-resource'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/v1/mcp'
    | '/api/v1/.well-known/oauth-protected-resource'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/v1/mcp'
    | '/api/v1/.well-known/oauth-protected-resource'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1McpRoute: typeof ApiV1McpRoute
  ApiV1DotwellKnownOauthProtectedResourceRoute: typeof ApiV1DotwellKnownOauthProtectedResourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/mcp': {
      id: '/api/v1/mcp'
      path: '/api/v1/mcp'
      fullPath: '/api/v1/mcp'
      preLoaderRoute: typeof ApiV1McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/.well-known/oauth-protected-resource': {
      id: '/api/v1/.well-known/oauth-protected-resource'
      path: '/api/v1/.well-known/oauth-protected-resource'
      fullPath: '/api/v1/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof ApiV1DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1McpRoute: ApiV1McpRoute,
  ApiV1DotwellKnownOauthProtectedResourceRoute:
    ApiV1DotwellKnownOauthProtectedResourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
